manifest:
  remotes:
    - name: urob
      url-base: https://github.com/urob
    - name: turnipblue                         # new entry
      url-base: https://github.com/TurnipBlue  # new entry
  projects:
    - name: zmk
      remote: urob
      revision: main
      import: app/west.yml
    - name: nice-view-module  # new entry
      remote: turnipblue      # new entry
      revision: main          # new entry
  self:
    path: config

